### ISSUE TITLE
How to get demo file ./public

### ISSUE THREAD

**Issue by zh3305** [rosenbjerg/Red#1]
How to get demo file ./public

**Comment by zh3305** [comment]
How to Use log

**Comment by rosenbjerg** [comment]
The logging plugin is registered to the RPluginCollection and can be obtained using `Plugins.Use<ILogger>()`. Then you just call the logging method that best fits your need on the object returned.
I am not quite sure what you mean by demo file

**Comment by rosenbjerg** [comment]
I am not sure what you meant by demo file. But i have updated the examples. I hope these can help you.

**Comment by zh3305** [comment]
Thank you
