### ISSUE TITLE
The connection was reset

### ISSUE THREAD

**Issue by CatboyCoding** [rosenbjerg/Red#16]
I'm trying to make an HTTP server and I'm getting this when trying to connect. Help?
![image](https://user-images.githubusercontent.com/45602120/74272242-98672980-4d0e-11ea-8c07-144bb244a927.png)
Code:
```csharp
        public async void startServer() {
            var server = new RedHttpServer(6969, path);

            server.Get("/screen.png", (req, res) => {
                string temp = Path.Combine(path, "screenshot.png");
                Bitmap bmp = Utils.Screenshot();
                bmp.Save(temp, ImageFormat.Png);
                res.AddHeader("Content-Type", "image/png");
                return res.SendFile(temp);
            });

            server.WebSocket("/ws", async (req, res) => {
                await res.SendText("Welcome to the GooseSocket!");
                res.OnTextReceived += async (sender, eventArgs) => {
                    string msg = eventArgs.Text;
                    string[] args = msg.Split(' ');
                    Event e = events.Where(c => c.name.Trim().Equals(args[0].Trim())).FirstOrDefault();
                    string result = "Invalid Event.";
                    if (e != null)
                        result = e.Run(args);
                    await res.SendText(result);
                };
                return HandlerType.Final;
            });

            await server.RunAsync();
        }
```

**Comment by rosenbjerg** [comment]
You shouldn't try to open the websocket url directly.
Instead, you should connect using a [WebSocket](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket):
`const connection = new WebSocket('ws://localhost:6969/ws')` in page javascript
you can then subscribe to events and send messages. See link above.
I'm closing this issue now, but please feel free to reopen if using the WebSocket class from javascript won't work

**Comment by LilSizzurp** [comment]
> 
> 
> You shouldn't try to open the websocket url directly.
> Instead, you should connect using a [WebSocket](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket):
> `const connection = new WebSocket('ws://localhost:6969/ws')` in page javascript
> you can then subscribe to events and send messages. See link above.
> I'm closing this issue now, but please feel free to reopen if using the WebSocket class from javascript won't work

i.. do that.
```javascript
var tasks = ["Wander", "TrackMud", "CollectMeme", "CollectNotepad", "NabMouse"]
var screen = {height:1080,width:1920}
var ws = new WebSocket("ws://"+location.host+"/ws");

ws.onmessage = (e) => {
    if(e.data.length == 0) return;
    alert(e.data);
}

ws.onclose = () => {
    alert("Connection closed.\r\nPlease refresh the webpage.");
    location.reload();
}

function cursorPos(e) {
    var rect = e.target.getBoundingClientRect();
    var curx = e.clientX - rect.left;
    var cury = e.clientY - rect.top;

    return {x:curx, y:cury}
}

var move = (m, e) => {
    var pos = cursorPos(e);
    var x = Math.floor(screen.width * (e.x / m.offsetWidth));
    var y = Math.floor(screen.height * (e.y / m.offsetHeight));
    ws.send(`move ${x} ${y}`);
}
var task = (t) => ws.send(`task ${t}`);
var honk = ( ) => ws.send("honk");
var stop = ( ) => ws.send("stop");

var update = () => {
    document.getElementById("screen").src = "screen.png#" + new Date().getTime()
};

setInterval(update, 100);
```

**Comment by CatboyCoding** [comment]
> 
> 
> You shouldn't try to open the websocket url directly.
> Instead, you should connect using a [WebSocket](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket):
> `const connection = new WebSocket('ws://localhost:6969/ws')` in page javascript
> you can then subscribe to events and send messages. See link above.
> I'm closing this issue now, but please feel free to reopen if using the WebSocket class from javascript won't work

i do that though, even visiting the **main page** gives that error.
![image](https://user-images.githubusercontent.com/45602120/74318615-e404ec00-4d7d-11ea-9fe0-bcb4ae75a4cc.png)

**Comment by rosenbjerg** [comment]
I assume you expect some index.html file from the `htdocs` folder to be served?
I cannot replicate this error. Instead I get 404 if no index.html exists in `htdocs`, and if I create one, I get served that one.

I used this:
`var server = new RedHttpServer(6969, "htdocs");`
And created the htdocs folder in [ProjectFolder]\bin\Debug\netcoreapp3.1

Can you please try something similar?
